/******************************************************************************
 * File Name:   main.c
 *
 * Description: This is the source code for the XMC MCU: Empty Application
 *              Template for ModusToolbox.
 *
 * Related Document: See README.md
 *
 ******************************************************************************
 *
 * Copyright (c) 2015-2021, Infineon Technologies AG
 * All rights reserved.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *****************************************************************************/

#include "XMC1100.h"
#include "cy_utils.h"
#include "cybsp.h"
#include "cycfg_peripherals.h"
#include "modes_states_pins.h"
#include "xmc_ccu4.h"
#include <math.h>
#include <stdint.h>

typedef struct __attribute__((packed)) {

  uint32_t header;

  uint8_t packetLength;

  uint16_t buffer[64];

} i2cPacket_t;

void parseData(uint16_t *buf) {

  uint16_t intBuf[64];

  uint8_t index = 0;

  for (index = 0; index < 64; index++) {
    intBuf[index] = buf[index];
  }
}

void HardFault_Handler() {
  PORT0->OMR = MODE_IDLE_OUT;
  PORT0->OMR = PIN_PRI_1_ON;
  PORT0->OMR = PIN_PRI_2_ON;
  while (true) {
  };
}

int main(void) {
  cy_rslt_t result;

  /* Initialize the device and board peripherals */
  result = cybsp_init();
  if (result != CY_RSLT_SUCCESS) {
    CY_ASSERT(0);
  }
  // Set default output
  PORT0->OMR = MODE_IDLE_OUT;
  
  i2cPacket_t i2cPacket;
  parseData(&i2cPacket.buffer[0]);
}

/* [] END OF FILE */
